### ISSUE TITLE
TempDeck: Current-Temperature intermittently shoots up to ~65,000 degrees

### ISSUE THREAD

**Issue by andySigler** [OpenTrons/opentrons-modules#14]
You can see in the image below, that the temperature returned from `Thermistor.plate_temperature()` shoots up to some impossibly high value.

The untested hypothesis is currently that it's because the firmware take up >80% of memory causing a runtime error.

![screen shot 2018-06-26 at 4 55 33 pm](https://user-images.githubusercontent.com/3085774/41990002-2f0dafa0-7a0f-11e8-9012-a3cfd0566188.png)

**Comment by sfoster1** [comment]
Stale
