### ISSUE TITLE
bug: heater-shaker: gcode cache seems to get full unexpectedly and stay full

### ISSUE THREAD

**Issue by sanni-t** [OpenTrons/opentrons-modules#352]
While testing [this home command bug](https://github.com/Opentrons/opentrons/issues/10858), I received a `gcode cache full` error. According to [this doc](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/512819201/Interaction+GCodes+and+Errors#Errors), this error is expected to be raised when a lot of gcode commands are received at once such that the input buffer is filled and the OS hasn't had a chance to address them yet. The error is supposed to go away once the commands get handled and the buffer is freed of space. But during my testing, it seemed like the cache was not being emptied as I kept receiving `gcode cache full` error on every gcode sent.

I will be re-testing this to add logs and more details

**Comment by pmoegenburg** [comment]
I couldn't reproduce with v0.4.4. I ran general_test.py multiple times following the protocol. Every 5 seconds, this routine was run: 1) close_plate_lock, 2) set_rpm, 3) home, 4) set_rpm. Because the bug fix to G28->M3 was not included in this firmware version, the final set_rpm returned an "ERR111:main motor:unable to move" every call.

**Comment by sanni-t** [comment]
Got it to reproduce on 0.4.6. I was sending an `M3 S500` right after a `G28` such that the homing action had started but not yet completed. The h/s would start slowing down as soon as it saw the `G28` but then as soon as it received the `M3` command, it would abandon homing and re-start shaking. The `M3` gets ACKed but looks like `G28` just gets forgotten in the cache. 

When the `G28`->`M3` that results in the error is sent, you can see that the `G28` gets ACKed finally because there's no space left for `M3` so it just gets rejected. 

I know this is quite an edge case and our API won't allow it happen but this case does reveal that the firmware might be abandoning requests mid-action (or doing that only for homing). I think the firmware shouldn't start addressing a new command if the current one hasn't been fully addressed. But if we do want individual commands to be interruptable (that's not a word?) then we should make sure that the previous command's execution is cleaned up. 
(Also made me wonder if we want to introduce a 'clear cache' gcode..)

```
M115
M115 FW:v0.4.6-de8fe19 HW:Opentrons Heater-Shaker SerialNo:HSDVT22041117 OK
M105
M105 C:25.02 T:None OK
M123
M123 C:0 T:0 OK
M241
M241 STATUS:IDLE_CLOSED OK
M242
M242 OK
M3 S500
ERR126:main motor:plate lock not closed (required)
G28
ERR126:main motor:plate lock not closed (required)
M3 S500
ERR126:main motor:plate lock not closed (required)
M243
M243 OK
G28
M3 S500
M3 OK
g28
ERR003:unhandled gcode
G28
G28 OK
..
ERR003:unhandled gcode
G28
M3 S500
M3 OK
M3 S500
M3 OK
.
ERR003:unhandled gcode
M3 S500.
ERR003:unhandled gcode
M3 900
ERR003:unhandled gcode
M3S900.
ERR003:unhandled gcode
M3 S900
M3 OK
G28 
M3 S500
M3 OK
G28
M3 S500
M3 OK
M3 S500
GM3 OK
28
M3 S500
ERR111:main motor:unable to move
M3 S500
M3 OK
G28
M3 S500
M3 OK
G28
M3 S500
M3 OK
G28
M3 S500
ERR004:gcode cache full
G28 OK

M3 S400
M3 OK
G28
G28 OK
G28 
M3 S400
ERR004:gcode cache full
G28 OK
G28
M3 S400
ERR004:gcode cache full
G28 OK
M3 ...
ERR003:unhandled gcode
G28
M3 S400
ERR004:gcode cache full
G28 OK
G28
M3 S400
ERR004:gcode cache full
G28 OK
M115
M115 FW:v0.4.6-de8fe19 HW:Opentrons Heater-Shaker SerialNo:HSDVT22041117 OK
M105
M105 C:25.81 T:None OK
G28
M3 S400
ERR004:gcode cache full
G28 OK
G28
M3 S400
ERR004:gcode cache full
G28 OK

```
