### ISSUE TITLE
Thermocycler: Lid Open and Close commands should use an interrupt

### ISSUE THREAD

**Issue by Laura-Danielle** [OpenTrons/opentrons-modules#55]
## Overview
As of now, the open and close lid commands are synchronous. This could cause issues down the line when the lid open/closing time could take a long time to complete. 

## Expected Behavior
Instead of increasing the timeout to an indefinite amount, we should refactor the `open_cover` and `close_cover` functions to return immediately and use an interrupt to update the lid status once a switch change is received.

**Comment by sanni-t** [comment]
It has been decided to increase `WAIT_FOR_ACK` to include the longest response time of thermocycler (i.e. open/close ACK) instead of having the firmware send an ACK right away.
Closing ticket.
